### PR TITLE
Fix: close downloaded files immediately

### LINKED ISSUE #138: Potential resource leak in `serveFetchDownload`
### Summary

We've observed a significant memory increase in our service using `goproxy` after upgrading to Go 1.25. Analysis of CPU and heap profiles suggests a potential resource leak in the `serveFetchDownload` function.

### Symptoms

- High and sustained memory usage, growing to multiple gigabytes.
- CPU profiles show significant time spent in syscalls related to network I/O and memory management (`runtime.madvise`).
- Heap profiles do not show a corresponding increase in Go heap objects, suggesting memory is held outside the Go runtime (e.g., goroutine stacks or file descriptors).

### Analysis

The `serveFetchDownload` function in `goproxy.go` calls `fetcher.Download`, which returns three `io.ReadSeekCloser` instances. These are closed in a `defer` block. If a panic occurs before the `defer` is executed (e.g., while caching files), these resources may not be closed, leading to a leak.

This issue seems to be exacerbated by a high volume of requests, such as those from a dependency update tool.

### Proposed Fix

Ensure that the `io.ReadSeekCloser` instances are closed in all execution paths, including error paths before the main `defer` statement is reached.

Memory usage after updating to Go 1.25 (spike coincided with a Renovate run which made lots of goproxy calls):

Image

The upgrade to Go 1.25, particularly with changes to the net/http package like the new CrossOriginProtection feature ([release notes](https://tip.golang.org/doc/go1.25)), likely altered the HTTP request lifecycle or error/panic handling in subtle ways. This change in behavior appears to be triggering the latent resource leak in goproxy more frequently, especially under the high load of a tool like Renovate.

### PR DESCRIPTION
**Pull request by echarrod**
This PR fixes a potential resource leak in the `serveFetchDownload` function by ensuring that the `info`, `mod`, and `zip` file handles are closed immediately after they are returned from the `fetcher.Download` function. This prevents file descriptors from being leaked in error paths.

Fixes #138

### CODE REVIEW

**Comment by echarrod** [comment]
I pointed our service at this fork + branch, and can see that the memory returns to normal after intensive renovate calls, unlike before, so pretty sure this is the fix 

image

File: goproxy.go [hunk 1]
```diff
@@ -274,11 +274,9 @@ func (g *Goproxy) serveFetchDownload(rw http.ResponseWriter, req *http.Request,
...
 		return
 	}
-	defer func() {
-		info.Close()
-		mod.Close()
-		zip.Close()
-	}()
+	defer info.Close()
+	defer mod.Close()
+	defer zip.Close()
```
Comment (aofei) [inline goproxy.go:279]: LGTM. The individual defer statements ensure all three `Close()` calls execute even if one panics. Thanks for the fix! 👍

**Review by aofei — APPROVED** [review]
